version: '3.8'
services:
    web:
        build:
            context: ./rubikoDocker
        ports:
            - '5050:5000'
        environment:
            - GREETINGS=Hello Rubiko Tech!
        depends_on:
            - curl
        networks:
            - my_network
    curl:
        image: curlimages/curl
        command: ['curl', 'http://web:5000/health']
        networks:
            - my_network

networks:
    my_network:
        driver: bridge
